Q1) Write a Python program to initialize a 3x3 NumPy array with any integer values of your choice. Then, perform the following operations: <br>
Multiply the entire array by 2. <br>
Add 5 to each element of the array. <br>
Calculate the square of each element in the array.<br>
Print the original array and the results of each operation.<br>

In [4]:
import numpy as np
table = np.array([[2,4,6], [3,5,7]])
print("Original", table)
print('Multiplied by 2', table * 2)
print('Added 5', table + 5)
print('Square', table * table)

Original [[2 4 6]
 [3 5 7]]
Multiplied by 2 [[ 4  8 12]
 [ 6 10 14]]
Added 5 [[ 7  9 11]
 [ 8 10 12]]
Square [[ 4 16 36]
 [ 9 25 49]]


Q2) Write a Python program to initialize a 3x3 NumPy array with any integer values of your choice. Then, perform the following slicing operations:
<br>Extract the first row of the array.
<br>Extract the last column of the array.
<br>Extract a 2x2 sub-array from the center of the original array.

In [17]:
print('First Row', table[0])
print('Last Row', table[1])
print("2*2 Array", table[:, 1:3])

First Row [2 4 6]
Last Row [3 5 7]
2*2 Array [[4 6]
 [5 7]]


Q3) Write a program to create a DataFrame in Python to store the names and marks of 10 students. <br>Each row of the DataFrame should represent a student, with columns as 'Name' and 'Marks'. <br>Populate the DataFrame with appropriate data and then print it.

In [19]:
import pandas as pd
data = {
    'Name': ['Dev', 'Hemang', 'Yash', 'Shreya', 'Shrehal', 'Shravani', 'Sandhya', 'Siddhi', 'Aastha', 'Nandini'],
    'Marks': [98, 85, 32, 20, 65, 74, 59, 35, 49, 25]
}
df = pd.DataFrame(data)
print(df)

       Name  Marks
0       Dev     98
1    Hemang     85
2      Yash     32
3    Shreya     20
4   Shrehal     65
5  Shravani     74
6   Sandhya     59
7    Siddhi     35
8    Aastha     49
9   Nandini     25


Q4) Write a python program to create a DataFrame representing the names and income of 5 employees. The DataFrame should include columns ' Employee_name’ and ‘Income', and each row should correspond to an individual employee. Use the indices 'a', 'b', 'c', 'd', and 'e' for the DataFrame entries to uniquely identify each employee.

In [22]:
emplData = {
    'Employee_Name': ['A', 'B', 'C', 'D', 'E','F'],
    'Marks': [98, 85, 32, 20, 65]
}
df = pd.DataFrame(emplData)
print(df)

ValueError: All arrays must be of the same length